//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agskeys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class assigned_table
    {
        public int id { get; set; }
        public string loanid { get; set; }
        public string assign_emp_id { get; set; }
        public string assign_vendor_id { get; set; }
        public string addedby { get; set; }
        public string datex { get; set; }
    }
}
