//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agskeys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class bank_table
    {
        public int id { get; set; }
                
        [Display(Name = "Bank")]
        [Required(ErrorMessage = "This field can not be empty.")]
        public string bankname { get; set; }

        [Display(Name = "Added By")]
        public string addedby { get; set; }

        [Display(Name = "Added Date")]
        public string datex { get; set; }
        
        [Display(Name = "Photo")]
        public string photo { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
