//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agskeys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class external_comment_table
    {
        public int id { get; set; }

        [Required(ErrorMessage = "You must enter External Comment")]
        [Display(Name = "External Comment")]
        public string externalcomment { get; set; }
        public string addedby { get; set; }
        public string datex { get; set; }
    }
}
