//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agskeys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class process_executive
    {
        public int id { get; set; }
        public string technical { get; set; }
        public string legal { get; set; }
        public string rcu { get; set; }
        public string comment { get; set; }
        public string addedby { get; set; }
        public string datex { get; set; }
        public string loanid { get; set; }
    }
}
