//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agskeys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proof_customer_table
    {
        public int id { get; set; }
        public string customerid { get; set; }
        public string proofid { get; set; }
        public string proofans { get; set; }
        public string addedby { get; set; }
        public string datex { get; set; }
    }
}
