//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agskeys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class proof_table
    {
        //[Key]
        public int id { get; set; }      

        [Display(Name = "Proof Name")]
        [Required(ErrorMessage = "Proof name cannot be empty.")]
        public string proofname { get; set; }

        [Display(Name = "Proof Order")]
        [Required(ErrorMessage = "You must choose proof order")]
        public string porder { get; set; }

        [Display(Name = "Status")]
        [Required(ErrorMessage = "This field cannot be empty.")]
        public string status { get; set; }

        [Display(Name = "Added Date")]
        public string datex { get; set; }

        [Display(Name = "Added By")]
        public string addedby { get; set; }
    }
}
