//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agskeys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vendor_track_table
    {
        public int id { get; set; }

        [Display(Name = "Loan Id")]
        public string loanid { get; set; }

        [Display(Name = "vendor Id")]
        public string vendorid { get; set; }

        [Display(Name = "Comment")]
        public string comment { get; set; }

        [Display(Name = "Track Time")]
        public string tracktime { get; set; }

        [Display(Name = "Added By")]
        public string addedby { get; set; }

        [Display(Name = "Added Date")]
        public string datex { get; set; }
    }
}
